resources:
- name: repo
  type: git
  icon: github
  source:
    uri: https://github.com/dharshan473/concourse-script

jobs:
- name: job
  public: true
  plan:
  - get: repo
    trigger: true
  - task: list-files
    config:
      inputs:
        - name: repo
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 'latest'
      run:
        path: sh
        args:
        - -exc
        - |
          echo "hello"