resources:
- name: my-git-repo1
  type: git
  source:
    uri: https://github.com/dharshan473/concourse-script
    branch: main
  check_every: 15s 

jobs:
- name: run-helloworld1
  plan:
  - get: my-git-repo1
    trigger: true
  - task: execute-helloworld1
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: ubuntu
          tag: 'latest'
      inputs:
      - name: my-git-repo1
      run:
        path: sh
        args:
        - -exc
        - |
          echo "hello"
          

